import { useEffect, useState, useCallback } from "react";
import { PieChart, Pie, Cell, Tooltip, Legend, ResponsiveContainer, BarChart, Bar, XAxis, YAxis, CartesianGrid } from "recharts";
import ErrorState from "../components/ErrorState";
import KPICard from "../components/KPICard";
import { getAssociationRules, getClusters, getDecisionTree } from "../api/mining";
import { getErrorMessage } from "../api/axios";
import { formatNumber, formatCompactINR, CHART_PALETTE, CHART_COLORS } from "../lib/format";

const TABS = [
  { id: "rules", label: "Association Rules" },
  { id: "clusters", label: "Patient Clusters" },
  { id: "tree", label: "Decision Tree Predictions" },
];

const CLUSTER_INFO = {
  "Low-Value Occasional": { color: "#64748b", desc: "Low overall spend with only 1–2 visits — infrequent, low-engagement patients." },
  "Regular Outpatient": { color: "#2653A6", desc: "Medium spend across 3–5 visits — steady outpatient follow-up patients." },
  "High-Value Regular": { color: "#0D9488", desc: "High spend with 5+ visits — the hospital's most valuable repeat patients." },
  "Emergency One-Time": { color: "#EF4444", desc: "Medium-to-high spend from a single emergency visit." },
  "Premium Insured": { color: "#F59E0B", desc: "High spend, typically backed by corporate or private insurance." },
};

export default function MiningPage() {
  const [tab, setTab] = useState("rules");

  return (
    <div className="space-y-4">
      <div>
        <h1 className="text-2xl font-bold text-navy">Mining Results</h1>
        <p className="text-sm text-slate-500">Association rules, patient clusters, and payment predictions</p>
      </div>

      <div className="rounded-lg bg-amber-50 border border-amber-200 text-amber-800 text-xs px-4 py-2.5">
        Mining results on this page were generated by <strong>KNIME Analytics Platform</strong> and{" "}
        <strong>Orange Data Mining</strong>. Python only reads and displays the stored results.
      </div>

      <div className="flex gap-1 border-b border-slate-200 overflow-x-auto">
        {TABS.map((t) => (
          <button
            key={t.id}
            onClick={() => setTab(t.id)}
            className={`px-4 py-2.5 text-sm font-medium border-b-2 -mb-px whitespace-nowrap transition-colors ${
              tab === t.id ? "border-teal text-teal" : "border-transparent text-slate-500 hover:text-slate-700"
            }`}
          >
            {t.label}
          </button>
        ))}
      </div>

      {tab === "rules" && <AssociationRulesTab />}
      {tab === "clusters" && <ClustersTab />}
      {tab === "tree" && <DecisionTreeTab />}
    </div>
  );
}

function AssociationRulesTab() {
  const [rules, setRules] = useState(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);

  const load = useCallback(() => {
    setLoading(true);
    setError("");
    getAssociationRules()
      .then(setRules)
      .catch((err) => setError(getErrorMessage(err)))
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  if (error) return <ErrorState message={error} onRetry={load} />;

  return (
    <div className="space-y-4">
      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-x-auto thin-scrollbar">
        <table className="w-full text-sm">
          <thead className="sticky top-0 bg-slate-50">
            <tr>
              {["Rule #", "Antecedent → Consequent", "Support", "Confidence", "Lift", "Date"].map((h) => (
                <th key={h} className="text-left px-4 py-3 font-semibold text-slate-600 border-b border-slate-200 whitespace-nowrap">
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {loading &&
              Array.from({ length: 8 }).map((_, i) => (
                <tr key={i}>
                  {Array.from({ length: 6 }).map((__, j) => (
                    <td key={j} className="px-4 py-3">
                      <div className="skeleton h-4 w-full" />
                    </td>
                  ))}
                </tr>
              ))}
            {!loading &&
              rules.map((r, i) => (
                <tr key={r.rule_id} className={`${i % 2 === 0 ? "bg-white" : "bg-slate-50/60"} hover:bg-teal-50`}>
                  <td className="px-4 py-2.5 text-slate-500">#{r.rule_id}</td>
                  <td className="px-4 py-2.5 text-slate-800 font-medium whitespace-nowrap">
                    {r.antecedent} <span className="text-teal">→</span> {r.consequent}
                  </td>
                  <td className="px-4 py-2.5 text-slate-600 tabular-nums">{r.support.toFixed(3)}</td>
                  <td className="px-4 py-2.5 text-slate-600 tabular-nums">{r.confidence_pct}%</td>
                  <td className="px-4 py-2.5 tabular-nums">
                    <span className={`font-semibold ${r.lift > 1.5 ? "text-sage" : "text-slate-600"}`}>
                      {r.lift.toFixed(2)}
                    </span>
                  </td>
                  <td className="px-4 py-2.5 text-slate-400 whitespace-nowrap">
                    {r.created_at ? new Date(r.created_at).toLocaleDateString() : "—"}
                  </td>
                </tr>
              ))}
          </tbody>
        </table>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 p-5">
        <h3 className="text-sm font-semibold text-navy mb-2">Reading Association Rules</h3>
        <p className="text-sm text-slate-600 leading-relaxed">
          Association Rules show which treatments frequently appear together. High confidence means "when patients
          have X, they very often also have Y." High lift means this co-occurrence is not random — the treatments
          are genuinely linked, not just individually common.
        </p>
      </div>
    </div>
  );
}

function ClustersTab() {
  const [clusters, setClusters] = useState(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);

  const load = useCallback(() => {
    setLoading(true);
    setError("");
    getClusters()
      .then(setClusters)
      .catch((err) => setError(getErrorMessage(err)))
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  if (error) return <ErrorState message={error} onRetry={load} />;

  return (
    <div className="space-y-4">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-5">
          <h3 className="text-sm font-semibold text-slate-800 mb-4">Patients per Cluster</h3>
          {loading || !clusters ? (
            <div className="skeleton h-64 w-full" />
          ) : (
            <ResponsiveContainer width="100%" height={280}>
              <PieChart>
                <Pie data={clusters} dataKey="patient_count" nameKey="cluster_name" innerRadius={60} outerRadius={100} paddingAngle={2}>
                  {clusters.map((c, i) => (
                    <Cell key={c.cluster_label} fill={CLUSTER_INFO[c.cluster_name]?.color || CHART_PALETTE[i % CHART_PALETTE.length]} stroke="#fff" strokeWidth={2} />
                  ))}
                </Pie>
                <Tooltip formatter={(v) => formatNumber(v)} />
                <Legend verticalAlign="bottom" height={48} formatter={(value) => <span className="text-xs text-slate-600">{value}</span>} />
              </PieChart>
            </ResponsiveContainer>
          )}
        </div>

        <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-x-auto thin-scrollbar">
          <table className="w-full text-sm">
            <thead className="bg-slate-50">
              <tr>
                {["Cluster", "Patients", "Avg Spent", "Avg Visits", "Avg Stay"].map((h) => (
                  <th key={h} className="text-left px-4 py-3 font-semibold text-slate-600 border-b border-slate-200 whitespace-nowrap">
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {loading || !clusters
                ? Array.from({ length: 5 }).map((_, i) => (
                    <tr key={i}>
                      {Array.from({ length: 5 }).map((__, j) => (
                        <td key={j} className="px-4 py-3">
                          <div className="skeleton h-4 w-full" />
                        </td>
                      ))}
                    </tr>
                  ))
                : clusters.map((c, i) => (
                    <tr key={c.cluster_label} className={i % 2 === 0 ? "bg-white" : "bg-slate-50/60"}>
                      <td className="px-4 py-2.5 font-medium text-slate-800 whitespace-nowrap">{c.cluster_name}</td>
                      <td className="px-4 py-2.5 tabular-nums">{formatNumber(c.patient_count)}</td>
                      <td className="px-4 py-2.5 tabular-nums">{formatCompactINR(c.avg_total_spent)}</td>
                      <td className="px-4 py-2.5 tabular-nums">{c.avg_visit_count}</td>
                      <td className="px-4 py-2.5 tabular-nums">{c.avg_avg_stay}d</td>
                    </tr>
                  ))}
            </tbody>
          </table>
        </div>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 p-5">
        <h3 className="text-sm font-semibold text-navy mb-3">Cluster Descriptions</h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {Object.entries(CLUSTER_INFO).map(([name, info]) => (
            <div key={name} className="flex items-start gap-2.5">
              <span className="w-3 h-3 rounded-full mt-1 shrink-0" style={{ backgroundColor: info.color }} />
              <div>
                <p className="text-sm font-semibold text-slate-800">{name}</p>
                <p className="text-xs text-slate-500">{info.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function DecisionTreeTab() {
  const [data, setData] = useState(null);
  const [page, setPage] = useState(1);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const pageSize = 10;

  const load = useCallback(() => {
    setLoading(true);
    setError("");
    getDecisionTree(page, pageSize)
      .then(setData)
      .catch((err) => setError(getErrorMessage(err)))
      .finally(() => setLoading(false));
  }, [page]);

  useEffect(() => {
    load();
  }, [load]);

  if (error) return <ErrorState message={error} onRetry={load} />;

  const totalPages = data ? Math.max(1, Math.ceil(data.total_count / pageSize)) : 1;

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <KPICard label="Predicted Paid" value={data ? formatNumber(data.predicted_paid) + " patients" : ""} tone="teal" loading={loading} />
        <KPICard label="Predicted Outstanding" value={data ? formatNumber(data.predicted_outstanding) + " patients" : ""} tone="coral" loading={loading} />
      </div>

      <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-5">
        <h3 className="text-sm font-semibold text-slate-800 mb-4">Prediction Confidence Distribution</h3>
        {loading || !data ? (
          <div className="skeleton h-64 w-full" />
        ) : (
          <ResponsiveContainer width="100%" height={260}>
            <BarChart data={data.confidence_distribution} margin={{ top: 4, right: 8, left: 8, bottom: 4 }}>
              <CartesianGrid stroke="#e2e8f0" vertical={false} />
              <XAxis dataKey="bucket" tick={{ fill: "#64748b", fontSize: 12 }} />
              <YAxis tick={{ fill: "#64748b", fontSize: 12 }} width={40} />
              <Tooltip formatter={(v) => formatNumber(v)} />
              <Bar dataKey="count" name="Predictions" fill={CHART_COLORS.navy} radius={[4, 4, 0, 0]} maxBarSize={50} />
            </BarChart>
          </ResponsiveContainer>
        )}
      </div>

      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-x-auto thin-scrollbar">
        <table className="w-full text-sm">
          <thead className="bg-slate-50">
            <tr>
              {["Patient ID", "Predicted Class", "Confidence", "Actual Class", "Match", "Created At"].map((h) => (
                <th key={h} className="text-left px-4 py-3 font-semibold text-slate-600 border-b border-slate-200 whitespace-nowrap">
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {loading || !data
              ? Array.from({ length: pageSize }).map((_, i) => (
                  <tr key={i}>
                    {Array.from({ length: 6 }).map((__, j) => (
                      <td key={j} className="px-4 py-3">
                        <div className="skeleton h-4 w-full" />
                      </td>
                    ))}
                  </tr>
                ))
              : data.predictions.map((p, i) => (
                  <tr key={p.prediction_id} className={i % 2 === 0 ? "bg-white" : "bg-slate-50/60"}>
                    <td className="px-4 py-2.5 tabular-nums">{p.patient_id}</td>
                    <td className="px-4 py-2.5">
                      <span
                        className={`text-xs font-semibold px-2 py-0.5 rounded ${
                          p.predicted_class === "Paid" ? "bg-emerald-100 text-sage" : "bg-red-100 text-coral"
                        }`}
                      >
                        {p.predicted_class}
                      </span>
                    </td>
                    <td className="px-4 py-2.5 tabular-nums">{p.confidence_pct}%</td>
                    <td className="px-4 py-2.5 text-slate-600">{p.actual_class || "—"}</td>
                    <td className="px-4 py-2.5">{p.match ? "✅" : "❌"}</td>
                    <td className="px-4 py-2.5 text-slate-400 whitespace-nowrap">
                      {p.created_at ? new Date(p.created_at).toLocaleDateString() : "—"}
                    </td>
                  </tr>
                ))}
          </tbody>
        </table>
      </div>

      <div className="flex items-center justify-end gap-1">
        <button
          disabled={page <= 1}
          onClick={() => setPage((p) => p - 1)}
          className="px-3 py-1.5 text-xs font-medium rounded-md border border-slate-300 disabled:opacity-40 hover:bg-slate-50"
        >
          Previous
        </button>
        <span className="text-xs text-slate-500 px-2">
          Page {page} of {totalPages}
        </span>
        <button
          disabled={page >= totalPages}
          onClick={() => setPage((p) => p + 1)}
          className="px-3 py-1.5 text-xs font-medium rounded-md border border-slate-300 disabled:opacity-40 hover:bg-slate-50"
        >
          Next
        </button>
      </div>
    </div>
  );
}
